apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g2d07e4w0-go
  janus-idp.io/tekton: g2d07e4w0-go
  backstage.io/kubernetes-id: g2d07e4w0-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: g2d07e4w0-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
